# fly.toml app configuration file generated for express-react-template on 2023-11-14T15:29:17-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "express-react-template"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
