# fly.toml app configuration file generated for members-only-ph on 2023-11-22T13:31:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "members-only-ph"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
